import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/toggle";

export const metadata: Metadata = {
  title: "react hook form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="p-4 w-full flex justify-end items-center">
            <ModeToggle/>
          </header>
          <main className="max-w-2xl mx-auto p-4">{children}</main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
